# Generated by Django 4.1.7 on 2023-03-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder_app', '0002_class_card_alter_about_img_alter_class_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
